#spring.jpa.database=POSTGRESQL
#spring.datasource.driver-class-name=${DATASOURCE_DRIVER}
#spring.jpa.database-platform=${JPA_DB_PLATFORM}
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username= ${DATASOURCE_USERNAME}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.jpa.properties.hibernate.dialect = ${HIBERNATE_DIALECT}
#spring.jpa.show-sql=${SHOW_SQL}
#spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
#
###JWT SECURITY
#security.token.access.secret-key=${ACCESS_TOKEN_SECRET}
#security.token.access.expiry-length=${ACCESS_TOKEN_EXPIRY}
#security.token.refresh.secret-key=${REFRESH_TOKEN_SECRET}
#security.token.refresh.expiry-length=${REFRESH_TOKEN_EXPIRY}
#
###CORS CONFIG
#cors.allowed-credential=${CORS_ALLOW}
#cors.allowed-origins =${CORS_ORIGIN}
#cors.allowed-headers= ${CORS_HEADERS}
#cors.allowed-methods = ${CORS_METHODS}
#
#
###PAYSTACK CONFIGURATION
#paystack.secret-key = ${PAY_STACK_KEY}
#paystack.initialize-payment-url = ${PAY_STACK_PAYMENT_URL}
#paystack.call-back-url = ${PAY_STACK_CALLBACK_URL}
#paystack.verification-url = ${PAY_STACK_VERIFICATION_URL}










############################
# SERVER
############################
server.port=8090


############################
# DATABASE / JPA
############################
spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/stitch
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=true


############################
# JWT SECURITY
############################
security.token.access.secret-key=2023BillantedChangeAccessKey
security.token.access.expiry-length=180000000

security.token.refresh.secret-key=2023BillantedChangeRefreshKey
security.token.refresh.expiry-length=43200000


############################
# CORS CONFIGURATION
############################
cors.allowed-credential=true
cors.allowed-origins=http://localhost:3000
cors.allowed-headers=Origin, X-Requested-With, Content-Type, Accept, Authorization
cors.allowed-methods=GET, POST, PUT, DELETE, OPTIONS

############################
# PAYSTACK CONFIGURATION
############################
paystack.secret-key=sk_test_e44b040732630cb4a313d4087b5ef8352e252ae0
paystack.initialize-payment-url=https://api.paystack.co/transaction/initialize
paystack.call-back-url=http://localhost:3000/orders/
paystack.verification-url=https://api.paystack.co/transaction/verify/

