#spring.jpa.database=POSTGRESQL
#spring.datasource.driver-class-name=${DATASOURCE_DRIVER}
#spring.jpa.database-platform=${JPA_DB_PLATFORM}
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username= ${DATASOURCE_USERNAME}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.jpa.properties.hibernate.dialect = ${HIBERNATE_DIALECT}
#spring.jpa.show-sql=${SHOW_SQL}
#spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
#
##JWT SECURITY
#security.token.access.secret-key=${ACCESS_TOKEN_SECRET}
#security.token.access.expiry-length=${ACCESS_TOKEN_EXPIRY}
#security.token.refresh.secret-key=${REFRESH_TOKEN_SECRET}
#security.token.refresh.expiry-length=${REFRESH_TOKEN_EXPIRY}
#
##CORS CONFIG
#cors.allowed-credential=${CORS_ALLOW}
#cors.allowed-origin =${CORS_ORIGIN}
#cors.allowed-header= ${CORS_HEADERS}
#cors.allowed-method = ${CORS_METHODS}
#
#
##PAYSTACK CONFIGURATION
#paystack.secret-key = ${PAY_STACK_KEY}
#paystack.initialize-payment-url = ${PAY_STACK_PAYMENT_URL}
#paystack.call-back-url = ${PAY_STACK_CALLBACK_URL}
#paystack.verification-url = ${PAY_STACK_VERIFICATION_URL}







spring.datasource.url=jdbc:postgresql://localhost:5432/stitch
# spring.datasource.url=jdbc:postgresql://dpg-cpr9rcjqf0us738b6qrg-a.oregon-postgres.render.com:5432/stitch_4ckz
# spring.datasource.username=stitchuser
# spring.datasource.password=z1LqmznSv7x0KhnvwaqF66fBcycYxEST
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show.sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none

spring.main.allow-bean-definition-overriding=false

server.port=8090

security.token.access.secret-key=2023BillantedChangeAccessKey
security.token.access.expiry-length=180000000
# millisecs (3000mins)
security.token.refresh.secret-key=2023BillantedChangeRefreshKey
security.token.refresh.expiry-length=43200000
# millisecs (12hrs)

graphql.altair.enabled=true
graphql.altair.mapping=/altair
graphql.altair.subscriptions.timeout=30
graphql.altair.subscriptions.reconnect=false
graphql.altair.static.base-path=/
graphql.altair.page-title=GraphQL
graphql.altair.options.endpoint-url=/graphql
graphql.altair.options.subscriptions-endpoint=/subscriptions
graphql.altair.options.initial-settings.theme=dracula

cors.allowed-credential=true
cors.allowed-origin=http://localhost:3000
cors.allowed-header=Origin, X-Requested-With, Content-Type, Accept, Authorization
cors.allowed-method=GET, POST, PUT, DELETE, OPTIONS

paystack.secret-key=sk_test_e44b040732630cb4a313d4087b5ef8352e252ae0
paystack.initialize-payment-url=https://api.paystack.co/transaction/initialize
paystack.call-back-url=http://localhost:4200/dashboard/orders/
paystack.verification-url=https://api.paystack.co/transaction/verify/