spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=${DATASOURCE_DRIVER}
spring.jpa.database-platform=${JPA_DB_PLATFORM}
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username= ${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect = ${HIBERNATE_DIALECT}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

#JWT SECURITY
security.token.access.secret-key=${ACCESS_TOKEN_SECRET}
security.token.access.expiry-length=${ACCESS_TOKEN_EXPIRY} #300 minutes
security.token.refresh.secret-key=${REFRESH_TOKEN_SECRET}
security.token.refresh.expiry-length=${REFRESH_TOKEN_EXPIRY} #12 hrs

#CORS CONFIG
cors.allowed-credential=${CORS_ALLOW}
cors.allowed-origins =${CORS_ORIGIN}
cors.allowed-headers= ${CORS_HEADERS}
cors.allowed-methods = ${CORS_METHODS}


#PAYSTACK CONFIGURATION
paystack.secret-key = ${PAY_STACK_KEY}
paystack.initialize-payment-url = ${PAY_STACK_PAYMENT_URL}
paystack.call-back-url = ${PAY_STACK_CALLBACK_URL}
paystack.verification-url = ${PAY_STACK_VERIFICATION_URL}