spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/stitch
    url: jdbc:postgresql://dpg-cpr9rcjqf0us738b6qrg-a.oregon-postgres.render.com:5432/stitch_4ckz
    username: stitchuser
    password: z1LqmznSv7x0KhnvwaqF66fBcycYxEST
#    username: postgres
#    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show.sql: true
    generate-ddl: true
    hibernate.ddl-auto: none


  main:
    allow-bean-definition-overriding: false


server:
  port: 8085




security:
  token:
    access:
      secret-key: 2023BillantedChangeAccessKey
      expiry-length: 1800000 # millisecs (30mins)
    refresh:
      secret-key: 2023BillantedChangeRefreshKey
      expiry-length: 43200000 #millisecs (12hrs)



graphql:
  altair:
    enabled: true
    mapping: /altair
    subscriptions:
      timeout: 30
      reconnect: false
    static:
      base-path: /
    page-title: GraphQL
    options:
      endpoint-url: /graphql
      subscriptions-endpoint: /subscriptions
      initial-settings:
        theme: dracula

cors:
  allowed-credential: true
  allowed-origin: "http://localhost:4200"
  allowed-header: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  allowed-method: "GET, POST, PUT, DELETE, OPTIONS"


paystack:
  secret-key: sk_test_e44b040732630cb4a313d4087b5ef8352e252ae0
  initialize-payment-url: https://api.paystack.co/transaction/initialize
  call-back-url: http://localhost:4200/dashboard/orders/
  verification-url: https://api.paystack.co/transaction/verify/